# Generated by Django 3.1.3 on 2020-11-28 19:26

import administracion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuId', models.AutoField(db_column='usu_id', primary_key=True, serialize=False)),
                ('usuCorreo', models.EmailField(db_column='usu_correo', max_length=254, unique=True, verbose_name='Correo')),
                ('usuNombre', models.CharField(db_column='usu_nombre', max_length=50)),
                ('usuFono', models.CharField(db_column='usu_fono', max_length=15)),
                ('usuDni', models.CharField(db_column='usuDni', default='pendiente', max_length=11, null=True)),
                ('usuDirec', models.CharField(db_column='usuDirec', default='pendiente', max_length=50, null=True)),
                ('usuPuesto', models.CharField(db_column='usuPuesto', default='pendiente', max_length=20, null=True)),
                ('usuDesper', models.CharField(db_column='usuDesper', default='pendiente', max_length=200, null=True)),
                ('usuDespro', models.CharField(db_column='usuDespro', default='pendiente', max_length=200, null=True)),
                ('password', models.TextField(db_column='usu_pass', null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 't_usuario',
            },
            managers=[
                ('objects', administracion.models.ManejoUsuario()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudModel',
            fields=[
                ('sol_id', models.AutoField(db_column='sol_id', primary_key=True, serialize=False, unique=True)),
                ('sol_nombre', models.CharField(db_column='sol_nombre', max_length=30)),
                ('sol_correo', models.CharField(db_column='sol_correo', max_length=40)),
                ('sol_telefono', models.CharField(db_column='sol_telefono', max_length=12)),
                ('sol_mensaje', models.CharField(db_column='sol_mensaje', max_length=200)),
                ('sol_estado', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('estado', models.BooleanField(default=True)),
                ('usuId', models.ForeignKey(db_column='usuId', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudesPersona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_solicitud',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('skill_id', models.AutoField(db_column='skill_id', primary_key=True, serialize=False, unique=True)),
                ('skill_nombre', models.CharField(db_column='skill_nombre', max_length=30)),
                ('skill_valoracion', models.DecimalField(db_column='skill_valoracion', decimal_places=2, max_digits=3)),
                ('skill_descripcion', models.CharField(db_column='skill_descripcion', max_length=100)),
                ('skill_url', models.CharField(db_column='skill_url', max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('estado', models.BooleanField(default=True)),
                ('usuId', models.ForeignKey(db_column='usuId', on_delete=django.db.models.deletion.PROTECT, related_name='skillsInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_skill',
            },
        ),
        migrations.CreateModel(
            name='ProyectoModel',
            fields=[
                ('proy_id', models.AutoField(db_column='proy_id', primary_key=True, serialize=False, unique=True)),
                ('proy_empresa', models.CharField(db_column='proy_empresa', max_length=20)),
                ('proy_nombre', models.CharField(db_column='proy_nombre', max_length=20)),
                ('proy_descripcion', models.CharField(db_column='proy_descripcion', max_length=150)),
                ('proy_duracion', models.CharField(db_column='proy_duracion', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('estado', models.BooleanField(default=True)),
                ('usuId', models.ForeignKey(db_column='usuId', on_delete=django.db.models.deletion.PROTECT, related_name='proyectosPersona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_proyecto',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaModel',
            fields=[
                ('exp_id', models.AutoField(db_column='exp_id', primary_key=True, serialize=False, unique=True)),
                ('exp_empresa', models.CharField(db_column='exp_empresa', max_length=20)),
                ('exp_puesto', models.CharField(db_column='exp_puesto', max_length=20)),
                ('exp_funciones', models.CharField(db_column='exp_funciones', max_length=150)),
                ('exp_duracion', models.CharField(db_column='exp_duracion', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('estado', models.BooleanField(default=True)),
                ('usuId', models.ForeignKey(db_column='usuId', on_delete=django.db.models.deletion.PROTECT, related_name='expesPersona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_experiencia',
            },
        ),
    ]
